# Generated by Django 6.0.1 on 2026-01-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, unique=True)),
                ('nombre_contacto', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_clientes/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='can_create_client',
            field=models.BooleanField(default=False, verbose_name='Puede crear clientes'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='can_delete_client',
            field=models.BooleanField(default=False, verbose_name='Puede eliminar clientes'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='can_edit_client',
            field=models.BooleanField(default=False, verbose_name='Puede editar clientes'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='can_upload_files',
            field=models.BooleanField(default=False, verbose_name='Puede subir archivos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='can_view_documents',
            field=models.BooleanField(default=True, verbose_name='Puede ver expedientes'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador Master'), ('analista_sr', 'Analista Senior'), ('analista_jr', 'Analista Junior')], default='analista_jr', max_length=20),
        ),
    ]
