# Generated by Django 6.0.1 on 2026-02-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='titulo',
            field=models.CharField(blank=True, help_text='Ej. Renovación de Licencias 2026', max_length=255, null=True, verbose_name='Título del Proyecto'),
        ),
    ]
