# Generated by Django 6.0.1 on 2026-01-26 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Formato')),
                ('archivo', models.FileField(upload_to='plantillas_word/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='Archivo Word (.docx)')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='datos_extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
