# Generated by Django 6.0.1 on 2026-02-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(default='MI DESPACHO S.A. DE C.V.', max_length=255)),
                ('rfc', models.CharField(default='AAA010101AAA', max_length=13)),
                ('regimen_fiscal', models.CharField(default='601', max_length=100)),
                ('codigo_postal', models.CharField(default='00000', max_length=5)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
