# Generated by Django 6.0.1 on 2026-01-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_plantilla_cliente_datos_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableEstandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Ej: nombre_empresa (sin corchetes)', max_length=100, unique=True)),
                ('descripcion', models.CharField(help_text='Ej: Razón Social del Cliente', max_length=255)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('fecha', 'Fecha'), ('numero', 'Número'), ('moneda', 'Moneda')], default='texto', max_length=20)),
                ('origen', models.CharField(choices=[('sistema', 'Automático del Sistema'), ('usuario', 'Input del Usuario')], default='usuario', max_length=20)),
                ('campo_bd', models.CharField(blank=True, help_text='Ej: cliente.nombre_empresa', max_length=100, null=True)),
            ],
        ),
    ]
