# Generated by Django 6.0.1 on 2026-02-06 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_cotizacion_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_convertido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedientes.cliente'),
        ),
    ]
