# Generated by Django 6.0.1 on 2026-01-26 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_variableestandar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Correo Electrónico'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('asunto', models.CharField(blank=True, help_text='Solo para Email', max_length=200)),
                ('cuerpo', models.TextField(help_text='Usa {cliente} para el nombre y {link} para el PDF.')),
                ('imagen_cabecera', models.ImageField(blank=True, help_text='Banner para el correo', null=True, upload_to='plantillas_img/')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospecto_nombre', models.CharField(max_length=200, verbose_name='Nombre del Prospecto')),
                ('prospecto_email', models.EmailField(max_length=254)),
                ('prospecto_telefono', models.CharField(max_length=20)),
                ('prospecto_empresa', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('validez_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada (Convertido)'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente_convertido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedientes.cliente')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_personalizada', models.TextField(blank=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expedientes.cotizacion')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedientes.servicio')),
            ],
        ),
    ]
