# Generated by Django 6.0.1 on 2026-02-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_factura_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='titulo_proyecto',
            field=models.CharField(default='Nuevo Proyecto Legal', max_length=200, verbose_name='Nombre del Proyecto'),
        ),
    ]
