# Generated by Django 6.0.1 on 2026-02-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='aplica_iva',
            field=models.BooleanField(default=False, verbose_name='¿Mas IVA?'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='total_con_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
