# Generated by Django 6.0.1 on 2026-02-07 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_cotizacion_aplica_iva_cotizacion_monto_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Tasa IVA (%)'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='aplica_iva',
            field=models.BooleanField(default=False, verbose_name='¿Lleva IVA?'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente_convertido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='expedientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20),
        ),
    ]
