# Generated by Django 6.0.1 on 2026-01-27 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_cuentaporcobrar_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('audiencia', 'Audiencia / Juzgado'), ('vencimiento', 'Vencimiento de Término'), ('reunion', 'Reunión con Cliente'), ('tramite', 'Trámite Administrativo'), ('personal', 'Recordatorio Personal')], default='reunion', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('completado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='expedientes.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
