# Generated by Django 6.0.1 on 2026-02-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_cotizacion_porcentaje_iva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='condiciones_pago',
            field=models.CharField(choices=[('50_50', '50% Anticipo - 50% al Finalizar'), ('100_entrega', '100% Contra Entrega de Resultados'), ('contado', 'Pago de Contado (Una sola exhibición)')], default='50_50', max_length=20, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tiempo_entrega',
            field=models.CharField(choices=[('30_dias', '30 Días Hábiles'), ('60_dias', '60 Días Hábiles'), ('90_dias', '90 Días Hábiles'), ('indefinido', 'Por definir según avance procesal')], default='30_dias', max_length=20, verbose_name='Tiempo de Gestión'),
        ),
    ]
