# Generated by Django 6.0.1 on 2026-01-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='avatares/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='clientes_asignados',
            field=models.ManyToManyField(blank=True, related_name='abogados_asignados', to='expedientes.cliente'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puesto',
            field=models.CharField(blank=True, help_text='Ej. Abogado Penalista', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador Master'), ('analista_sr', 'Abogado Senior'), ('analista_jr', 'Abogado Junior')], default='analista_jr', max_length=20),
        ),
    ]
