# Generated by Django 6.0.1 on 2026-02-10 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0007_cotizacion_condiciones_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_programados', to='expedientes.cotizacion'),
        ),
    ]
