# Generated by Django 6.0.1 on 2026-01-27 01:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0007_usuario_avatar_usuario_clientes_asignados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='prospecto_nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='cotizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expedientes.cotizacion'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('audiencia', 'Audiencia'), ('vencimiento', 'Vencimiento'), ('reunion', 'Reunión'), ('tramite', 'Trámite'), ('personal', 'Personal')], default='reunion', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='archivo',
            field=models.FileField(upload_to='plantillas_word/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])]),
        ),
        migrations.AlterField(
            model_name='plantillamensaje',
            name='asunto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plantillamensaje',
            name='cuerpo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plantillamensaje',
            name='imagen_cabecera',
            field=models.ImageField(blank=True, null=True, upload_to='plantillas_img/'),
        ),
        migrations.AlterField(
            model_name='plantillamensaje',
            name='tipo',
            field=models.CharField(choices=[('email', 'Correo'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='puesto',
            field=models.CharField(blank=True, help_text='Ej. Abogado Sr.', max_length=100),
        ),
        migrations.AlterField(
            model_name='variableestandar',
            name='campo_bd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variableestandar',
            name='clave',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='variableestandar',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='variableestandar',
            name='origen',
            field=models.CharField(default='usuario', max_length=20),
        ),
        migrations.AlterField(
            model_name='variableestandar',
            name='tipo',
            field=models.CharField(default='texto', max_length=20),
        ),
    ]
