# Generated by Django 6.0.1 on 2026-02-11 04:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0008_alter_cuentaporcobrar_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEnlace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_externas', to='expedientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='uploads_pendientes/')),
                ('nombre_requisito', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_temp', to='expedientes.solicitudenlace')),
            ],
        ),
    ]
