# Generated by Django 6.0.1 on 2026-01-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0008_alter_cotizacion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='access_agenda',
            field=models.BooleanField(default=False, verbose_name='Acceso a Agenda'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='access_contratos',
            field=models.BooleanField(default=False, verbose_name='Acceso a Generador Contratos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='access_cotizaciones',
            field=models.BooleanField(default=False, verbose_name='Acceso a Cotizaciones'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='access_disenador',
            field=models.BooleanField(default=False, verbose_name='Acceso a Diseñador'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='access_finanzas',
            field=models.BooleanField(default=False, verbose_name='Acceso a Finanzas'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='can_create_client',
            field=models.BooleanField(default=False, verbose_name='Crear Clientes'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='can_delete_client',
            field=models.BooleanField(default=False, verbose_name='Eliminar Clientes'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='can_edit_client',
            field=models.BooleanField(default=False, verbose_name='Editar Clientes'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='Gestionar Usuarios'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='can_upload_files',
            field=models.BooleanField(default=False, verbose_name='Subir Archivos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='can_view_documents',
            field=models.BooleanField(default=True, verbose_name='Ver Documentos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='puesto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
