# Generated by Django 6.0.1 on 2026-01-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0010_alter_usuario_access_agenda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Campo (Ej. RFC)')),
                ('tipo', models.CharField(choices=[('text', 'Texto Corto (Ej. RFC)'), ('textarea', 'Texto Largo (Ej. Dirección)'), ('date', 'Fecha (Ej. Cumpleaños)'), ('number', 'Número (Ej. Edad)')], default='text', max_length=20)),
                ('obligatorio', models.BooleanField(default=False)),
            ],
        ),
    ]
