# Generated by Django 6.0.1 on 2026-01-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0011_campoadicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='campoadicional',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campoadicional',
            name='tipo',
            field=models.CharField(choices=[('text', 'Texto Corto'), ('textarea', 'Texto Largo'), ('date', 'Fecha'), ('number', 'Número')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre_archivo',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='evento',
            name='inicio',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('pausado', 'En Pausa'), ('finalizado', 'Finalizado')], db_index=True, default='abierto', max_length=20),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='num_expediente',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='access_agenda',
            field=models.BooleanField(default=False, verbose_name='Acceso Agenda'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='access_contratos',
            field=models.BooleanField(default=False, verbose_name='Acceso Contratos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='access_cotizaciones',
            field=models.BooleanField(default=False, verbose_name='Acceso Cotizaciones'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='access_disenador',
            field=models.BooleanField(default=False, verbose_name='Acceso Diseñador'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='access_finanzas',
            field=models.BooleanField(default=False, verbose_name='Acceso Finanzas'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='can_create_client',
            field=models.BooleanField(default=False, verbose_name='Crear Clientes'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='can_delete_client',
            field=models.BooleanField(default=False, verbose_name='Eliminar Clientes'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='can_edit_client',
            field=models.BooleanField(default=False, verbose_name='Editar Clientes'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='Gestionar Usuarios'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='can_upload_files',
            field=models.BooleanField(default=False, verbose_name='Subir Archivos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='can_view_documents',
            field=models.BooleanField(default=True, verbose_name='Ver Documentos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador Master'), ('analista_sr', 'Abogado Senior'), ('analista_jr', 'Abogado Junior')], db_index=True, default='analista_jr', max_length=20),
        ),
    ]
