# Generated by Django 6.0.1 on 2026-01-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0012_alter_bitacora_fecha_alter_campoadicional_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacion',
            name='valores_adicionales',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='servicio',
            name='campos_dinamicos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
